
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/teste-1042/18-alpine', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/teste-1042/18-alpine']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'api-teste-gcp2', '--image', 'gcr.io/teste-1042/18-alpine', '--region', 'us-central1', '--platform', 'managed', '--port', '3000']
images:
- gcr.io/teste-1042/18-alpine