name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMAGE_NAME: gcr.io/${{secrets.GCP_PROJECT_ID}}/site:latest
      SERVICE_NAME: hello # Nome do seu serviço, altere conforme necessário
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{secrets.GCP_CREDENTIALS}}
          project_id: ${{secrets.GCP_PROJECT_ID}}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # build image
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t $IMAGE_NAME .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # deploy image with new service name for force recreation
      - name: Deploy Docker image
        run: |
          gcloud run deploy $SERVICE_NAME --image $IMAGE_NAME --region us-central1 --memory 128Mi --min-instances 1 --max-instances 1 --platform managed --port 3000 --allow-unauthenticated
    env:
      SERVICE_NAME: "hello-$(date +%Y%m%d%H%M%S)"  # Adicione um sufixo de data/hora para criar um nome de serviço exclusivo
