name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # build image
      - name: Build Docker image
        run:  docker buildx build --platform linux/amd64 -t teste-1042 .
      # push image to registry
      - name: Push Docker image
        run: docker push gcr.io/teste-1042/18-alpine

      # deploy image
      - name: Deploy Docker image
        run: gcloud run deploy hello-00001-zz7 --image gcr.io/teste-1042/18-alpine --region us-central1 --memory 128Mi --min-instances 1 --max-instances 2 --platform managed --port 3000 --allow-unauthenticated